export const types = Object.freeze({
  // Sync
  FORECAST_START_FETCHING: "FORECAST_START_FETCHING",
  FORECAST_STOP_FETCHING: "FORECAST_STOP_FETCHING",
  FORECAST_FILL: "FORECAST_FILL",
  FORECAST_SET_FETCHING_ERROR: "FORECAST_SET_FETCHING_ERROR",
  FORECAST_SELECT_DAY: "FORECAST_SELECT_DAY",
  FORECAST_FILTER: "FORECAST_FILTER",
  // Async
  FORECAST_FETCH_ASYNC: "FORECAST_FETCH_ASYNC"
});
